require(plyr)
require(stringr)
source('~/Documents/DataSets/TwitterSentiment//twitterConnect.R')
tweets <- searchTwitter("#pakistan",lang="en", n=200, cainfo="cacert.pem")
Tweets.txt <- laply(tweets, function(t)t$getText())
pos <- scan("~/Documents/DataSets//TwitterSentiment/positive_words.txt", what='character', comment.char=';')
neg <- scan("~/Documents/DataSets/TwitterSentiment/negative_words.txt", what='character', comment.char=';')
source('~/Documents/DataSets/TwitterSentiment//scoreSentiment.R')
analysis = score.sentiment(Tweets.txt, pos, neg)
table(analysis$score)
mean(analysis$score)
hist(analysis$score)
plot(density(analysis$score))
